name: Build  And Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - name: build web
        run: cd web && npm install && npm run build


      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mv -r web/dist/* src/main/resources/static/ && mvn  -q package

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
            target/*.zip
